Base Model: meta-llama/Llama-3.1-8B

In [1]:
!pip install -q "transformers==4.47.1"  "accelerate==1.3.0"

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 336.6/336.6 kB 8.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 3.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 66.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 36.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 54.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 3.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 9.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 5.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 47.2 MB/s eta 0:00:00


In [2]:
from transformers import AutoModelForCausalLM, AutoTokenizer

model_name = "deepseek-ai/DeepSeek-R1-Distill-Llama-8B"

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype="auto",
    device_map="auto"
)
tokenizer = AutoTokenizer.from_pretrained(model_name)

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/826 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/24.2k [00:00<?, ?B/s]

model-00001-of-000002.safetensors:   0%|          | 0.00/8.67G [00:00<?, ?B/s]

model-00002-of-000002.safetensors:   0%|          | 0.00/7.39G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/181 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/3.06k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.08M [00:00<?, ?B/s]

In [3]:
prompt = """find differention of f(x) = 2x^2+sin(x)/3x^2
"""

messages = [
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": prompt}
]
text = tokenizer.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True
)
model_inputs = tokenizer([text], return_tensors="pt").to(model.device)

generated_ids = model.generate(
    **model_inputs,
    max_new_tokens=2048
)
generated_ids = [
    output_ids[len(input_ids):] for input_ids, output_ids in zip(model_inputs.input_ids, generated_ids)
]

response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]

print(response)

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.


<think>
I need to find the derivative of the function \( f(x) = \frac{2x^2 + \sin(x)}{3x^2} \).

First, I'll simplify the function by separating the terms in the numerator.

Next, I'll apply the quotient rule to differentiate the function, which involves taking the derivative of the numerator and the denominator separately.

After calculating the derivatives, I'll simplify the expression to obtain the final derivative.
</think>

To find the differentiation of the function \( f(x) = \frac{2x^2 + \sin(x)}{3x^2} \), follow these steps:

### Step 1: Simplify the Function
First, rewrite the function to separate the terms:

\[
f(x) = \frac{2x^2}{3x^2} + \frac{\sin(x)}{3x^2}
\]

Simplify each term:

\[
f(x) = \frac{2}{3} + \frac{\sin(x)}{3x^2}
\]

### Step 2: Differentiate Term by Term
Differentiate each term separately.

1. **First Term: \( \frac{2}{3} \)**
   \[
   \frac{d}{dx}\left(\frac{2}{3}\right) = 0
   \]

2. **Second Term: \( \frac{\sin(x)}{3x^2} \)**
   Use the quotient rule:
   \[


In [4]:
prompt = """There are two numbers 9.99 and 9.12, what is the biggest number
"""

messages = [
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": prompt}
]
text = tokenizer.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True
)
model_inputs = tokenizer([text], return_tensors="pt").to(model.device)

generated_ids = model.generate(
    **model_inputs,
    max_new_tokens=500
)
generated_ids = [
    output_ids[len(input_ids):] for input_ids, output_ids in zip(model_inputs.input_ids, generated_ids)
]

response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]

print(response)

Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.


<think>
First, I need to identify the two numbers provided: 9.99 and 9.12.

To compare these numbers accurately, I'll align their decimal places by writing them with the same number of decimal places.

Once they are aligned, I can compare each digit starting from the left. Both numbers have the same whole number part, which is 9.

Next, I'll compare the tenths place: 9 in 9.99 is greater than 1 in 9.12.

Since the tenths place of 9.99 is larger, I can conclude that 9.99 is the bigger number.
</think>

**Solution:**

To determine which number is larger between **9.99** and **9.12**, follow these steps:

1. **Align the Decimal Places:**

   It's helpful to write both numbers with the same number of decimal places for an accurate comparison.

   \[
   \begin{align*}
   9.99 \\
   9.12 \\
   \end{align*}
   \]

2. **Compare the Numbers Digit by Digit:**

   - **Whole Number Part:**
     - Both numbers have the same whole number part: **9**.

   - **Tenths Place:**
     - Compare the tenths

<think>
First, I need to identify the two numbers provided: 9.99 and 9.12.

To compare these numbers accurately, I'll align their decimal places by writing them with the same number of decimal places.

Once they are aligned, I can compare each digit starting from the left. Both numbers have the same whole number part, which is 9.

Next, I'll compare the tenths place: 9 in 9.99 is greater than 1 in 9.12.

Since the tenths place of 9.99 is larger, I can conclude that 9.99 is the bigger number.
</think>

**Solution:**

To determine which number is larger between **9.99** and **9.12**, follow these steps:

1. **Align the Decimal Places:**

   It's helpful to write both numbers with the same number of decimal places for an accurate comparison.

   \[
   \begin{align*}
   9.99 \\
   9.12 \\
   \end{align*}
   \]

2. **Compare the Numbers Digit by Digit:**

   - **Whole Number Part:**
     - Both numbers have the same whole number part: **9**.

   - **Tenths Place:**
     - Compare the tenths place:
       - **9** (from 9.99) vs. **1** (from 9.12)
     - **9** is greater than **1**.

3. **Conclusion:**

   Since the tenths place of **9.99** is greater than that of **9.12**, we can determine that:

   \[
   \boxed{9.99 \text{ is the bigger number}}
   \]